In [1]:
import pandas as pd

In [2]:
questions=pd.read_csv('questions.csv',sep='\t',index_col=0)

In [3]:
questions=questions.T
questions

question                        Idquest  parent  type  Treatment
UNIQUE ID                           NaN     NaN   NaN        NaN
start                               NaN     NaN   NaN        NaN
end                                 NaN     NaN   NaN        NaN
today                               NaN     NaN   NaN        NaN
deviceid                            NaN     NaN   NaN        NaN
...                                 ...     ...   ...        ...
_index                              NaN     NaN   NaN        NaN
Interview Status(Keep/Exclude)      NaN     NaN   NaN        NaN
Region_clean                        NaN     NaN   NaN        NaN
District_clean                      NaN     NaN   NaN        NaN
Mode of data collection             NaN     NaN   NaN        NaN

[889 rows x 4 columns]

In [4]:
questions.Idquest=questions.Idquest.astype('string')
questions.type=questions.type.astype('string')
questions.Treatment=questions.Treatment.astype('string')
questions.Idquest

UNIQUE ID                         <NA>
start                             <NA>
end                               <NA>
today                             <NA>
deviceid                          <NA>
                                  ...
_index                            <NA>
Interview Status(Keep/Exclude)    <NA>
Region_clean                      <NA>
District_clean                    <NA>
Mode of data collection           <NA>
Name: Idquest, Length: 889, dtype: string

In [5]:
questions.index

Index(['UNIQUE ID', 'start', 'end', 'today', 'deviceid', 'phonenumber',
       'audit', 'audit_URL', 'Are you conducting a Test or a Valid entry?',
       'Is this survey done on a call center or physically in the field?',
       ...
       '_validation_status', '_notes', '_status', '_submitted_by', '_tags',
       '_index', 'Interview Status(Keep/Exclude)', 'Region_clean',
       'District_clean', 'Mode of data collection'],
      dtype='object', length=889)

In [6]:
kobo=pd.read_csv('kobo_file.csv',sep='\t')
kobo.head(30)

,type,name,label
0,start,start,NaN
1,end,end,NaN
2,today,today,NaN
3,deviceid,deviceid,NaN
4,phonenumber,phonenumber,NaN
5,audit,audit,NaN
6,select_one testvalid,testvalid,Are you conducting a Test or a Valid entry?
7,select_one ccorfield,ccorfield,Is this survey done on a call center or physic...
8,date,date1,Survey Start Date
9,time,time1,Survey Start Time
10,calculate,starttime,NaN
11,calculate,startdate,NaN
12,begin_group,rc,Respondent's Consent
13,note,noteform,My name is ____(Data collectorâ€™s name) and I a...
14,note,note,"Your participation is fully intended, and even..."
15,select_one Consent,Consent,I agree to take part in this interview.
16,select_one Consent,Consent1,I appreciate the objectives of the research an...
17,select_one Consent,Consent2,I know how to contact Axiom ME to limit or can...
18,select_one Consent,Consent3,I understand that my personal information used...
19,select_one Consent,Consent4,I agree that you may contact me in the future ...
20,select_one Consent,Consent5,I agree to having my words used as quotes in t...
21,select_one Consent,Consent6,I am of the same mind to having my name and in...
22,end_group,NaN,NaN
23,begin_group,enumeratordetails,Enumerator Section
24,text,enumname,Enumerator's name
25,select_one gender,enumgender,Enumerator's gender
26,geopoint,gps,GPS
27,select_one region,region,Region
28,select_one district,district,District
29,select_one targetlocation,targetlocation,Target location

In [7]:
[i for i in kobo.label if i==i and "\\" in i]

[]

In [8]:
[i for i in kobo.type.unique() if 'select' not in i]

['start',
 'end',
 'today',
 'deviceid',
 'phonenumber',
 'audit',
 'date',
 'time',
 'calculate',
 'begin_group',
 'note',
 'end_group',
 'text',
 'geopoint',
 'integer',
 'decimal']

In [9]:
'A24) Why did you settle in this location?/Availability'.split('/')

['A24) Why did you settle in this location?', 'Availability']

In [10]:
for i in range(383):
    if kobo.loc[i]['label']==kobo.loc[i]['label']:
        for quest in questions.index:
            if kobo.loc[i]['label']==quest:
                questions.at[quest,'Idquest']=kobo.loc[i]['name']
                if kobo.loc[i]['type']=='decimal':
                    questions.at[quest,'type']='continue'
            elif kobo.loc[i]['label'] in quest and '/' in quest:
                questions.at[quest,'Idquest']=kobo.loc[i]['name']+' '+quest.split('/')[-1]
                questions.at[quest,'Treatment']='cat'

In [11]:
questions.T.to_csv('questions_auto.csv',sep='\t')

In [12]:
questions[questions.Idquest==questions.Idquest]

question,Idquest,parent,type,Treatment
Are you conducting a Test or a Valid entry?,testvalid,NaN,<NA>,<NA>
Is this survey done on a call center or physically in the field?,ccorfield,NaN,<NA>,<NA>
Survey Start Date,date1,NaN,<NA>,<NA>
Survey Start Time,time1,NaN,<NA>,<NA>
"My name is ____(Data collectorâ€™s name) and I am working with NRC and we are doing Multi sector needs assessment. The purpose is to assess the current humanitarian situation, the needs and priorities in the locations NRC is currently implementing programs. The findings of this assessment will help us identify the needs/gaps along NRCâ€™s core competencies (Program areas) such as: LFS, WASH, ICLA, Shelter vis-Ã -vis the Impact of COVID-19 pandemic. Your personal information and the responses you give will remain strictly confidential and anonymous, will only be used for analysis and reporting. You have full discretion to not participate the exercise in whole or part.",noteform,NaN,<NA>,<NA>
...,...,...,...,...
J14) How are they related to you?/Other.1,relationship5 Other.1,NaN,<NA>,cat
"J15) If other, please specify:",relationship5_other,NaN,<NA>,<NA>
Survey end time,time2,NaN,<NA>,<NA>
Survey end date,date2,NaN,<NA>,<NA>
Thank you for participating in this survey; Your feedback is highly appreciated,thanksnote,NaN,<NA>,<NA>